---
- name: Install istio on a k8s cluster
  hosts: all

  tasks:

    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml
      
        
    - name: run shell script
      include: run.yml
